name: dbt_run_scheduled
run-name: dbt_run_scheduled

on:
  workflow_dispatch:
  # schedule:
  #   # Runs "every 10 minutes, 5 mins after the realtime job
  #   - cron: "5,15,25,35,45,55 * * * *"

env:
  USE_VARS: "${{ vars.USE_VARS }}"
  DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR }}"
  DBT_VERSION: "${{ vars.DBT_VERSION }}"
  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ vars.WAREHOUSE }}"
  SCHEMA: "${{ vars.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/dbt_run_template.yml@@AN-4374/upgrade-dbt-1.7
    with:
      dbt_command: >
        dbt run -s tag:core
      environment: workflow_prod
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit
